apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-master
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: {{ include "n8n.fullname" . }}-master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: {{ include "n8n.fullname" . }}-webhook 
---
{{- if .Values.config.redis.deployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
{{- end }} 